title: "Mike Silaev's Portfolio"
description: "Machine learning, quantum physics, data science, and robotics enthusiast"
baseurl: ""
url: "https://msilaev.github.io"
github_username: msilaev

# Social Links
linkedin: https://www.linkedin.com/in/mike-silaev-1b7b1678/
google_scholar: https://scholar.google.com/citations?user=PMj0KZIAAAAJ&hl=ru
portfolio: https://msilaev.github.io

# Theme settings
theme: minima

# Plugins
plugins:
  - jekyll-feed

# Markdown settings
markdown: kramdown
highlighter: rouge

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
